config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  devise_for :users

  resources :projects do
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                :integer          not null, primary key
#  user_id           :integer
#  name              :string
#  short_description :text
#  description       :text
#  image_url         :string
#  status            :string           default("pending")
#  goal              :decimal(8, 2)
#  expiration_date   :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :rewards
  validates :name,:short_description, :description, :image_url, :goal, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project

  validates :description, :value, :estimated_delivery, presence: true
  validates :value, numericality: { greater_than_or_equal_to: 0 }
  validates :number_available, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :estimated_delivery, date: { after: Date.today }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  customer_id            :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.all
    @displayed_projects = Project.take(4)
  end

  def show
  end

  def edit
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created" }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end  
  end

  
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated" }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to project_path, notice: "Project was successfully destroyed" }
      format.json { head :no_content }      
    end
  end
  
  private 
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :short_description, :description, :goal, :image_url, :expiration_date)
    end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project
  before_action :set_reward, except: [:new , :create]

  def new
    @reward = @project.rewards.build
    respond_to do |format|
      format.html
    end
  end

  def create
     @reward = @project.rewards.build(reward_params)
     respond_to do |format|
      if @reward.save
          format.html { redirect_to @project, notice: "Reward was successfully created" }
      else
        format.html {render 'new'}
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @project, notice: "Reward was successfully updated" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to projects_path(@project), notice: "Reward was successfully destroyed" }
    end
  end


  private 
    def set_project
      @project = Project.find(params[:project_id])
    end
      
    def reward_params
      params.require(:reward).permit(:name, :description, :value, :shipping, :number_available, :estimated_delivery)
    end 

    def set_reward
      @reward = @project.rewards.find(params[:id])
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Crowd-Funding</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
        <li><%= link_to "Start a Project"  %></li>
        <li><%= link_to "Account"  %></li>
        <li><%= link_to "Signout" , destroy_user_session_path , method: :delete  %></li>
        <% else %>
        <li><%= link_to "Sign-Up" ,  new_user_registration_path %></li>
        <li><%= link_to "Log-In" , new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/projects/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% projects.count.times do |i| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= "active" if i.zero? %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% projects.each_with_index do |project,index| %>
      <div class="item <%= "active" if index.zero? %>">
        <img src="<%= project.image_url %>" alt="...">
        <div class="carousel-caption">
          <div class="container">
            <h2><%= project.name %></h2>
            <p><%= project.short_description %></p>
            <%= link_to "View Project", project_path(project), class: "btn btn-success btn-lg" %>
          </div>
        </div>
      </div>  
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :short_description %>
  <%= f.input :description, as: :wysihtml5 %>
  <%= f.input :goal %>
  <%= f.input :image_url %>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col-md-4 col-sm-6 col-xs-12">

 <div class="project-box">
  <%= link_to image_tag(project.image_url, alt: project.name, width: '100%', height: '200px'), project_path(project) %>
  <div class="description-box">
    <div class="title">
      <%= link_to project.name, "#" %>
    </div>
    <div class="description">
      <%= project.short_description %>
    </div>
    <div class="project-bar">
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= funded %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= funded %>">
          <span class="sr-only"><%= funded %> Complete (Success)</span>
        </div>
      </div>
    </div>

    <!-- Project Stats -->
    <div class="stats">
      <ul>
        <!-- percentage of funding -->
        <li>100% <br><span class="label">funded</span></li>
        <!-- total amount pledged (dollars) -->
        <li>$1000 <br><span class="label">pledged</span></li>
        <!-- days to go 'till deadline -->
        <li>10 <br><span class="label">days to go</span></li>
      </ul>
      </div>

    </div>
  </div>

</div>

app/views/projects/_stats.html.erb
<div class="project-stats">
  <div class="row">

    <!-- number of backers -->
    <div class="col-xs-4 col-sm-12">
      <div class="val">
        10
      </div>
      <div class="lab">
        backers
      </div>
    </div>

    <!-- goal -->
    <div class="col-xs-4 col-sm-12">
      <div class="val">
        1000$
      </div>
      <div class="lab">
        goal
      </div>
    </div>

    <!-- days to go -->
    <div class="col-xs-4 col-sm-12">
      <div class="val">
        4
      </div>
      <div class="lab">
        days to go
      </div>
    </div>

  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Editing Project</h1>
  <%= render 'form' %>

  <%= link_to 'Show', @project %>
  <%= link_to 'Back', projects_path %>
</div

app/views/projects/index.html.erb
<% if @displayed_projects.any? %>

  <%= render "projects/carousel" %>

    <div class="container">
    <br><br><br>
      <h3 class="project-subtitle">Our Project</h3>
      <div class="row">
        <%= render "project" %>
      </div>
    </div>

<% else %>

  <div class="container text-center">
    <br><br><br>
    <h2>Create your first project</h2>
    <%= link_to "Start project!", new_project_path, class: "btn btn-success btn-lg" %>
  </div>

<% end %>

app/views/projects/new.html.erb
<div class="container">
  <h1>New Project</h1>
  <%= render "form"%>
</div>

app/views/projects/show.html.erb
<div class="project-intro">
  <div class="container">
    
    <!-- project name -->
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="project-title"><%= @project.name %></h2>
      </div>
    </div>

    <!-- stats -->
    <div class="row">
      <div class="col-md-8">
        <%= link_to image_tag(@project.image_url, alt: @project.name, width: '100%'), project_path(@project) %>
      </div>
      <div class="col-md-4">
        <div class="project-mgmt">
          <%= link_to 'Edit', edit_project_path(@project) %>
          <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <%= render 'stats' %>
        <%= link_to 'See project backers', "#", class: "btn btn-success btn-lg" %>
        <%= link_to 'Back this project', "#", class: "btn btn-success btn-lg" %>
        <p class="project-time">This project will expire in 3 days.</p>
      </div>
    </div>

    <!-- small description -->
    <div clas="row">
      <div class="col-md-8">
        <p class="project-small-description">Project small description.</p>
      </div>
    </div>
  </div>
</div>

<!-- rewards -->
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="project-subtitle">Rewards</h3>
      <p><%= @project.description %></p>
    </div>
    <div class="col-md-4">
      <p>Rewards will be rendered in here ...</p>
      <%= link_to 'Add Reward', new_project_reward_path(@project), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/rewards/_form.html.erb
<%= simple_form_for([@project , @reward], html: {class: "form-horizontal"}) do |f|%>
  <%= f.input :description %>
  <%= f.input :value %>
  <%= f.input :shipping %>
  <%= f.input :number_available %>
  <%= f.input :estimated_delivery, :as => :date_picker %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<div class="container">
  <h1>Edit Reward</h1>
  <%= render "form"%>
</div>

app/views/rewards/new.html.erb
<div class="container">
  <h1>Add a new reward</h1>
  <%= render 'form' %>
</div>